---
sidebar: sidebar 
permalink: second-gen/beegfs-design-solution-sizing-guidelines.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS 솔루션에는 검증 테스트를 기반으로 한 성능 및 용량 사이징에 대한 권장 사항이 포함되어 있습니다. 
---
= 사이징 지침
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS 솔루션에는 검증 테스트를 기반으로 한 성능 및 용량 사이징에 대한 권장 사항이 포함되어 있습니다.

빌딩 블록 아키텍처의 목표는 특정 BeeGFS 시스템의 요구 사항을 충족하기 위해 여러 빌딩 블록을 추가하여 간편하게 사이징할 수 있는 솔루션을 구축하는 것입니다. 아래 지침에 따라 환경 요구 사항을 충족하는 데 필요한 BeeGFS 빌딩 블록의 양과 유형을 예측할 수 있습니다.

이러한 추정치는 최상의 성능을 제공하는 것으로, 가상 벤치마킹 애플리케이션은 실제 애플리케이션이 사용할 수 없는 방식으로 기본 파일 시스템의 사용을 최적화하기 위해 작성 및 사용됩니다.



== 성능 사이징

다음 표에는 권장되는 성능 사이징이 나와 있습니다.

|===
| 구성 프로파일 | 1MiB 읽기 | 1MiB의 쓰기입니다 


| 메타데이터 + 스토리지 | 62GiBps | 21GiBps 


| 스토리지만 해당 | 64GiBps | 21GiBps 
|===
메타데이터 용량 사이징 예상치는 "경험 규칙"을 기반으로 하며, 이 경우 500GB의 용량으로 BeeGFS에서 약 1억 5천만 개의 파일을 저장할 수 있습니다. (자세한 내용은 BeeGFS 설명서를 참조하십시오 https://doc.beegfs.io/latest/system_design/system_requirements.html["시스템 요구 사항"^]참조)

액세스 제어 목록, 디렉터리별 디렉토리 및 파일 수와 같은 기능을 사용하면 메타데이터 공간이 얼마나 빨리 소비되는지를 알 수 있습니다. 스토리지 용량 추정치는 RAID 6 및 XFS 오버헤드와 함께 사용 가능한 드라이브 용량을 고려합니다.



== 메타데이터 + 스토리지 구성 요소에 대한 용량 사이징

다음 표에는 메타데이터와 스토리지 구성 요소에 권장되는 용량 사이징이 나와 있습니다.

|===
| 드라이브 크기(2+2 RAID 1) 메타데이터 볼륨 그룹 | 메타데이터 용량(파일 수) | 드라이브 크기(8 + 2 RAID 6) 스토리지 볼륨 그룹 | 스토리지 용량(파일 콘텐츠) 


| 1.92TB | 1,938,577,200 | 1.92TB | 51.77TB 


| 3.84TB | 3,880,388,400 | 3.84TB | 103.55TB 


| 7.68TB | 8,125,278,000입니다 | 7.68TB | 216.74TB 


| 15.3TB | 17,269,854,000 | 15.3TB | 460.60TB 
|===

NOTE: 메타데이터 및 스토리지 구성 요소의 크기를 조정할 때 더 작은 드라이브를 메타데이터 볼륨 그룹에 사용하는 것과 스토리지 볼륨 그룹을 사용하는 것을 통해 비용을 절감할 수 있습니다.



== 스토리지 전용 구성 요소에 대한 용량 사이징

다음 표에는 스토리지 전용 구성 요소에 대한 경험 많은 용량 사이징이 나와 있습니다.

|===
| 드라이브 크기(10 + 2 RAID 6) 스토리지 볼륨 그룹 | 스토리지 용량(파일 콘텐츠) 


| 1.92TB | 59.89TB 


| 3.84TB | 119.80TB 


| 7.68TB | 251.89TB 


| 15.3TB | 538.55TB 
|===

NOTE: 글로벌 파일 잠금이 활성화되지 않은 경우 기본(첫 번째) 구성 요소에서 관리 서비스를 포함할 때 발생하는 성능 및 용량 오버헤드가 최소화됩니다.
