---
sidebar: sidebar 
permalink: beegfs-deploy-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 2세대 NetApp BeeGFS 빌딩 블록 설계를 사용하여 NetApp에서 검증된 파일 및 블록 노드에 BeeGFS를 구축할 수 있습니다. 
---
= 구축 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
2세대 NetApp BeeGFS 빌딩 블록 설계를 사용하여 NetApp에서 검증된 파일 및 블록 노드에 BeeGFS를 구축할 수 있습니다.



== Ansible 컬렉션 및 역할

Ansible을 사용하여 NetApp 솔루션에 BeeGFS를 구축할 수 있습니다. 이는 애플리케이션 구축을 자동화하는 데 사용되는 일반적인 IT 자동화 엔진입니다. Ansible은 구축할 BeeGFS 파일 시스템을 모델링하는 인벤토리로 통칭되는 일련의 파일을 사용합니다.

Ansible을 사용하면 NetApp과 같은 기업에서 Ansible Galaxy의 컬렉션을 사용하여 기본 제공 기능을 확장할 수 있습니다(참조) https://galaxy.ansible.com/netapp_eseries["NetApp E-Series BeeGFS 컬렉션"^])를 클릭합니다. 컬렉션에는 E-Series 볼륨 만들기와 같이 특정 기능 또는 작업을 수행하는 모듈과 여러 모듈 및 기타 역할을 호출할 수 있는 역할이 포함되어 있습니다. 이 자동화된 방식을 통해 BeeGFS 파일 시스템 및 기본 HA 클러스터를 구축하는 데 필요한 시간을 줄일 수 있습니다. 또한, 기존 파일 시스템을 확장하기 위해 구성 요소를 간단하게 추가할 수 있습니다.

자세한 내용은 을 참조하십시오 link:beegfs-deploy-learn-ansible.html["Ansible 인벤토리에 대해 알아보십시오"].


NOTE: NetApp 솔루션에 BeeGFS를 구축하는 데 다양한 단계가 포함되므로 NetApp에서는 수동으로 솔루션 구축을 지원하지 않습니다.



== BeeGFS 구성 요소에 대한 구성 프로필입니다

배포 절차는 다음과 같은 구성 프로파일을 다룹니다.

* 관리, 메타데이터 및 스토리지 서비스를 포함하는 하나의 기본 구성 요소입니다.
* 메타데이터와 스토리지 서비스가 포함된 두 번째 구성 요소입니다.
* 스토리지 서비스만 포함하는 세 번째 구성 요소입니다.


이러한 프로필을 통해 NetApp BeeGFS 구성 요소에 대한 권장 구성 프로필 전체 범위를 볼 수 있습니다. 각 구축에 필요한 메타데이터 및 스토리지 구성 요소 수 또는 스토리지 서비스 전용 구성 요소는 용량 및 성능 요구사항에 따라 절차에 따라 달라질 수 있습니다.



== 배포 단계 개요

배포에는 다음과 같은 고급 작업이 포함됩니다.

.하드웨어 구축
. 각 구성 요소를 물리적으로 조립합니다.
. 랙 및 케이블 하드웨어. 자세한 절차는 를 참조하십시오 link:beegfs-deploy-hardware.html["하드웨어 구축"].


.소프트웨어 구축
. link:beegfs-deploy-setup-nodes.html["파일 및 블록 노드 설정"].
+
** 파일 노드에서 BMC IP를 구성합니다
** 지원되는 운영 체제를 설치하고 파일 노드에서 관리 네트워킹을 구성합니다
** 블록 노드에서 관리 IP를 구성합니다


. link:beegfs-deploy-setting-up-an-ansible-control-node.html["Ansible 제어 노드를 설정합니다"].
. link:beegfs-deploy-file-node-tuning.html["성능을 위해 시스템 설정을 조정합니다"].
. link:beegfs-deploy-create-inventory.html["Ansible 인벤토리를 작성합니다"].
. link:beegfs-deploy-define-inventory.html["BeeGFS 구성 요소에 대한 Ansible 인벤토리를 정의합니다"].
. link:beegfs-deploy-playbook.html["Ansible을 사용하여 BeeGFS 구축"].
. link:beegfs-deploy-configure-clients.html["BeeGFS 클라이언트를 구성합니다"].



NOTE: 배포 절차에는 텍스트를 파일로 복사해야 하는 몇 가지 예제가 포함되어 있습니다. 특정 배포에 대해 수정하거나 수정할 수 있는 모든 사항에 대해 "#" 또는 "//" 문자로 표시된 인라인 코멘트에 세심한 주의를 기울이십시오. 예를 들어, ``begfs_ha_ntp_server_pool:# 이것은 설명의 예입니다! "pool 0.pool.ntp.org iburst maxsources 3" - "pool 1.pool.ntp.org iburst maxsources 3"
