---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Ansible 제어 노드를 설정하려면 솔루션을 구성하는 데 사용할 수 있는 모든 파일 및 블록 노드의 관리 포트에 대한 네트워크 액세스를 갖춘 가상 머신 또는 물리적 머신을 식별합니다. 
---
= Ansible 제어 노드를 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ansible 제어 노드를 설정하려면 NetApp 솔루션 기반 BeeGFS 솔루션용으로 구축된 모든 파일 및 블록 노드에 대한 네트워크 액세스가 가능한 가상 머신 또는 물리적 머신을 지정해야 합니다.

권장되는 패키지 버전 목록은 를 link:beegfs-technology-requirements.html#ansible-control-node-requirements["기술 요구사항"]참조하십시오. 다음 단계는 Ubuntu 22.04에서 테스트되었습니다. 선호하는 Linux 배포와 관련된 단계는 를 https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Ansible 설명서"^]참조하십시오.

. Ansible 제어 노드에서 다음 Python 및 Python 가상 환경 패키지를 설치합니다.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Python 가상 환경을 만듭니다.
+
[source, console]
----
python3 -m venv ~/pyenv
----
. 가상 환경을 활성화합니다.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. 활성화된 가상 환경 내에 필요한 Python 패키지를 설치합니다.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Ansible Galaxy를 사용하여 BeeGFS 컬렉션을 설치합니다.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. 설치된 Ansible, Python 및 BeeGFS 컬렉션 버전이 과 일치하는지 확인합니다link:beegfs-technology-requirements.html#ansible-control-node-requirements["기술 요구사항"].
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Ansible이 Ansible 제어 노드에서 원격 BeeGFS 파일 노드에 액세스할 수 있도록 암호 없는 SSH를 설정합니다.
+
.. 필요한 경우 Ansible 제어 노드에서 공용 키 쌍을 생성합니다.
+
[source, console]
----
ssh-keygen
----
.. 각 파일 노드에 암호 없는 SSH를 설정합니다.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





CAUTION: 블록 노드에 암호 없는 SSH를 * 설정하지 마십시오. 이 작업은 지원되거나 필요하지 않습니다.
