---
sidebar: sidebar 
permalink: administer-clusters-reconfigure.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, Ansible, pcs 
summary: Ansible을 사용하여 클러스터를 재구성합니다. 
---
= HA 클러스터와 BeeGFS를 재구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible을 사용하여 클러스터를 재구성합니다.



== 개요

일반적으로 BeeGFS HA 클러스터의 모든 측면을 재구성할 때는 Ansible 인벤토리를 업데이트하고 을 다시 실행해야 합니다 `ansible-playbook` 명령. 여기에는 알림 업데이트, 영구 펜싱 구성 변경 또는 BeeGFS 서비스 구성 조정 등이 포함됩니다. 이러한 설정은 를 사용하여 조정합니다 `group_vars/ha_cluster.yml` 파일 및 전체 옵션 목록은 에서 찾을 수 있습니다 link:custom-architectures-inventory-common-file-node-configuration.html["일반 파일 노드 구성을 지정합니다"^] 섹션을 참조하십시오.

유지 관리를 수행하거나 클러스터를 서비스할 때 관리자가 알아야 하는 구성 옵션에 대한 자세한 내용은 아래를 참조하십시오.



== 펜싱 비활성화 및 활성화 방법

클러스터를 설정할 때 펜싱은 기본적으로 활성화/필요합니다. 경우에 따라 펜싱을 일시적으로 비활성화하여 운영 체제 업그레이드와 같은 특정 유지보수 작업을 수행할 때 노드가 실수로 종료되지 않도록 하는 것이 좋습니다. 이 기능은 수동으로 비활성화할 수 있지만 관리자가 주의해야 할 단점이 있습니다.



=== 옵션 1: Ansible을 사용하여 펜싱 비활성화(권장)

Ansible을 사용하여 펜싱을 비활성화하면 BeeGFS 모니터의 장애 발생 시 동작이 "fence"에서 "standby"로 변경됩니다. 즉, BeeGFS 모니터가 장애를 감지하면 노드를 대기 상태로 두고 모든 BeeGFS 서비스를 페일오버하려고 합니다. 활성 상태의 문제 해결/테스트 이외의 경우 일반적으로 옵션 2보다 더 권장됩니다. 단점은 리소스가 원래 노드에서 중지되지 않을 경우 다른 위치에서 시작하는 것이 차단된다는 것입니다(즉, 펜싱은 일반적으로 운영 클러스터에 필요합니다).

. 에 있는 Ansible 인벤토리에 들어 있습니다 `groups_vars/ha_cluster.yml` 다음 구성을 추가합니다.
+
[source, console]
----
beegfs_ha_cluster_crm_config_options:
    stonith-enabled: False
----
. Ansible 플레이북을 다시 실행하여 클러스터의 변경 사항을 적용합니다.




=== 옵션 2: 수동으로 펜싱을 비활성화합니다.

경우에 따라 Ansible을 다시 실행하지 않고 펜싱을 일시적으로 비활성화할 수 있으며, 클러스터에 대한 문제 해결 또는 테스트를 용이하게 할 수 있습니다.


WARNING: 이 구성에서 BeeGFS 모니터가 장애를 감지하면 클러스터가 해당 리소스 그룹을 중지하려고 시도합니다. 전체 페일오버를 트리거하거나 영향을 받는 리소스 그룹을 다시 시작하거나 다른 호스트로 이동하려고 시도하지 않습니다. 복구하려면 문제를 해결한 다음 를 실행하십시오 `pcs resource cleanup` 또는 노드를 수동으로 대기 상태로 전환합니다.

단계:

. 펜싱(STONITH)이 전역적으로 활성화 또는 비활성화되었는지 확인하려면 다음을 실행하십시오. `pcs property show stonith-enabled`
. 펜싱 실행을 비활성화하려면: `pcs property set stonith-enabled=false`
. 펜싱 실행을 활성화하려면: `pcs property set stonith-enabled=true`


참고: 이 설정은 다음 번에 Ansible 플레이북을 실행할 때 재정의됩니다.
