---
sidebar: sidebar 
permalink: custom-architectures-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Ansible을 실행하기 전에 파일 및 블록 노드를 설정하는 데 필요한 수동 단계 
---
= 파일 및 블록 노드 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible을 실행하기 전에 파일 및 블록 노드를 설정하는 데 필요한 수동 단계



== 파일 노드



=== 베이스보드 관리 컨트롤러(BMC) 구성

서비스 프로세서라고도 하는 베이스보드 관리 컨트롤러(BMC)는 다양한 서버 플랫폼에 내장되어 운영 체제가 설치되어 있지 않거나 액세스할 수 없는 경우에도 원격 액세스를 제공할 수 있는 대역외 관리 기능의 일반 이름입니다. 공급업체는 일반적으로 고유한 브랜딩으로 이 기능을 마케팅합니다. 예를 들어, Lenovo SR665에서 BMC는 Lenovo XClarity Controller(XCC)라고 합니다.

서버 공급업체의 설명서에 따라 이 기능에 액세스하는 데 필요한 모든 라이센스를 활성화하고 BMC가 네트워크에 연결되고 원격 액세스에 맞게 구성되었는지 확인합니다.


NOTE: Redfish를 사용하여 BMC 기반 펜싱을 사용하려면 Redfish가 활성화되어 있고 파일 노드에 설치된 OS에서 BMC 인터페이스에 액세스할 수 있어야 합니다. BMC와 운영 체제가 동일한 물리적 네트워크 인터페이스를 공유하는 경우 네트워크 스위치에 특별한 구성이 필요할 수 있습니다.



=== 시스템 설정을 조정합니다

시스템 설정(BIOS/UEFI) 인터페이스를 사용하여 성능을 최대화하도록 설정이 설정되어 있는지 확인합니다. 정확한 설정과 최적의 값은 사용 중인 서버 모델에 따라 달라집니다. 에 대한 지침이 제공됩니다 link:beegfs-deploy-file-node-tuning.html["파일 노드 모델을 확인했습니다"^], 그렇지 않으면 해당 모델에 따라 서버 공급업체의 설명서 및 모범 사례를 참조하십시오.



=== 운영 체제를 설치합니다

나열된 파일 노드 요구 사항에 따라 지원되는 운영 체제를 설치합니다 link:beegfs-technology-requirements.html#file-node-requirements["여기"^]. Linux 배포판에 따라 아래의 추가 단계를 참조하십시오.



==== RedHat

RedHat 서브스크립션 관리자를 사용하여 시스템을 등록 및 구독하여 공식 Red Hat 리포지토리에서 필요한 패키지를 설치하고 지원되는 Red Hat 버전으로 업데이트를 제한할 수 있습니다. `subscription-manager release --set=<MAJOR_VERSION>.<MINOR_VERSION>`. 자세한 내용은 을 참조하십시오 https://access.redhat.com/solutions/253273["RHEL 시스템을 등록하고 가입하는 방법"^] 및  https://access.redhat.com/solutions/2761031["업데이트 제한 방법"^].

고가용성을 위해 필요한 패키지가 포함된 Red Hat 리포지토리를 활성화합니다.

....
subscription-manager repo-override --repo=rhel-8-for-x86_64-highavailability-rpms --add=enabled:1
....


=== 관리 네트워크를 구성합니다

운영 체제의 대역 내 관리를 허용하는 데 필요한 네트워크 인터페이스를 구성합니다. 정확한 단계는 사용 중인 특정 Linux 배포 및 버전에 따라 다릅니다.


NOTE: SSH가 활성화되어 있고 Ansible 제어 노드에서 모든 관리 인터페이스에 액세스할 수 있는지 확인합니다.



=== HCA 및 HBA 펌웨어를 업데이트합니다

모든 HBA 및 HCA가 에 나열된 지원되는 펌웨어 버전을 실행하고 있는지 확인합니다 link:https://imt.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 필요한 경우 업그레이드합니다. NVIDIA ConnectX 어댑터에 대한 추가 권장 사항을 찾을 수 있습니다 link:beegfs-technology-requirements.html#file-node-requirements["여기"^].



== 블록 노드

의 단계를 따릅니다 link:https://docs.netapp.com/us-en/e-series/getting-started/getup-run-concept.html["E-Series와 함께 가동 및 운영합니다"^] 각 블록 노드 컨트롤러에서 관리 포트를 구성하고 선택적으로 각 시스템의 스토리지 어레이 이름을 설정합니다.


NOTE: Ansible 제어 노드에서 모든 블록 노드에 액세스할 수 있도록 보장하는 추가 구성은 필요하지 않습니다. 나머지 시스템 구성은 Ansible을 사용하여 적용/유지합니다.
