---
sidebar: sidebar 
permalink: administer-clusters-examine-state.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs 
summary: PC를 사용하여 클러스터의 상태를 봅니다. 
---
= 클러스터의 상태를 검사합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
PC를 사용하여 클러스터의 상태를 봅니다.



== 개요

실행 중입니다 `pcs status` 모든 클러스터 노드에서 클러스터의 전체 상태와 각 리소스의 상태(예: BeeGFS 서비스 및 해당 종속성)를 확인하는 가장 쉬운 방법입니다. 이 섹션에서는 의 출력에서 확인할 수 있는 내용을 설명합니다 `pcs status` 명령.



== 의 출력 이해 `pcs status`

실행 `pcs status` 클러스터 서비스(박동조율기 및 Corosync)가 시작되는 모든 클러스터 노드에서. 출력 맨 위에는 클러스터의 요약이 표시됩니다.

[source, console]
----
[root@beegfs_01 ~]# pcs status
Cluster name: hacluster
Cluster Summary:
  * Stack: corosync
  * Current DC: beegfs_01 (version 2.0.5-9.el8_4.3-ba59be7122) - partition with quorum
  * Last updated: Fri Jul  1 13:37:18 2022
  * Last change:  Fri Jul  1 13:23:34 2022 by root via cibadmin on beegfs_01
  * 6 nodes configured
  * 235 resource instances configured
----
아래 섹션에는 클러스터의 노드가 나열됩니다.

[source, console]
----
Node List:
  * Node beegfs_06: standby
  * Online: [ beegfs_01 beegfs_02 beegfs_04 beegfs_05 ]
  * OFFLINE: [ beegfs_03 ]
----
이는 대기 또는 오프라인 상태인 노드를 나타냅니다. 대기 상태의 노드는 여전히 클러스터에 참여하고 있지만 리소스 실행 부적격으로 표시되어 있습니다. 오프라인 상태인 노드는 노드가 수동으로 중지되었거나 노드가 재부팅/종료되었기 때문에 해당 노드에서 클러스터 서비스가 실행되고 있지 않음을 나타냅니다.


NOTE: 노드가 처음 시작될 때 클러스터 서비스가 중지되며, 비정상적인 노드로 리소스가 실수로 페일백되지 않도록 수동으로 시작해야 합니다.

노드가 비관리적 이유(예: 실패)로 인해 대기 또는 오프라인 상태인 경우 노드의 상태 옆에 괄호 안에 추가 텍스트가 표시됩니다. 예를 들어 펜싱을 사용하지 않도록 설정하고 리소스에 장애가 발생하면 표시됩니다 `Node <HOSTNAME>: standby (on-fail)`. 다른 가능한 상태는 입니다 `Node <HOSTNAME>: UNCLEAN (offline)`펜싱이 실패하여 클러스터가 노드 상태를 확인할 수 없음을 나타내는 경우(다른 노드에서 리소스가 시작되는 것을 차단할 수 있음) 잠시 노드가 펜싱되는 것으로 나타나지만 지속합니다.

다음 섹션에는 클러스터의 모든 리소스 목록과 해당 상태가 표시됩니다.

[source, console]
----
Full List of Resources:
  * mgmt-monitor	(ocf::eseries:beegfs-monitor):	 Started beegfs_01
  * Resource Group: mgmt-group:
    * mgmt-FS1	(ocf::eseries:beegfs-target):	 Started beegfs_01
    * mgmt-IP1	(ocf::eseries:beegfs-ipaddr2):	 Started beegfs_01
    * mgmt-IP2	(ocf::eseries:beegfs-ipaddr2):	 Started beegfs_01
    * mgmt-service	(systemd:beegfs-mgmtd):	 Started beegfs_01
[...]
----
노드와 마찬가지로 리소스에 문제가 있는 경우 괄호 안의 리소스 상태 옆에 추가 텍스트가 표시됩니다. 예를 들어 페이스 메이커의 리소스 중지를 요청했으나 할당된 시간 내에 완료되지 못한 경우 심장박동기는 노드를 울타리로 만들려고 시도합니다. 펜싱이 비활성화되거나 펜싱 작업이 실패하는 경우 리소스 상태는 입니다 `FAILED <HOSTNAME> (blocked)` 다른 노드에서 심장박동조율기를 시작할 수 없습니다.

BeeGFS HA 클러스터가 여러 BeeGFS에 최적화된 맞춤형 OCF 리소스 에이전트를 사용하는 것을 주목할 필요가 있습니다. 특히 BeeGFS 모니터는 특정 노드의 BeeGFS 리소스를 사용할 수 없을 때 페일오버를 트리거합니다.
