---
sidebar: sidebar 
permalink: administer/clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: HA 클러스터를 관리하기 위해 Ansible과 PCS 명령줄 도구를 사용해야 하는 경우는 언제입니까? 
---
= Ansible과 PCS 도구를 사용해야 하는 경우
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
HA 클러스터를 관리하기 위해 Ansible과 PCS 명령줄 도구를 사용해야 하는 경우는 언제입니까?

모든 클러스터 배포 및 재구성 작업은 외부 Ansible 제어 노드의 Ansible을 사용하여 완료해야 합니다. 클러스터 상태의 일시적인 변경(예: 대기 모드 내외부로 노드 배치)은 일반적으로 클러스터의 한 노드(성능이 저하되지 않거나 유지 보수를 수행하려고 하지 않는 노드)에 로그인하고 PCS 명령줄 도구를 사용하여 수행됩니다.

리소스, 제약, 속성 및 BeeGFS 서비스 자체를 비롯한 클러스터 구성을 수정하려면 항상 Ansible을 사용해야 합니다. Ansible 인벤토리 및 플레이북의 최신 복사본(소스 제어 기능을 통해 변경 사항을 추적하는 것이 이상적)을 유지하는 것은 클러스터를 유지하는 데 필요한 부분입니다. 구성을 변경해야 하는 경우 인벤토리를 업데이트하고 BeeGFS HA 역할을 가져오는 Ansible 플레이북을 다시 실행합니다.

HA 역할은 클러스터를 유지 관리 모드로 설정한 다음 필요한 변경을 수행한 후 BeeGFS 또는 클러스터 서비스를 다시 시작하여 새 구성을 적용하는 작업을 처리합니다. 전체 노드 재부팅은 일반적으로 초기 구현 이후에 필요하지 않기 때문에 Ansible을 다시 실행하는 것은 일반적으로 "안전한" 절차로 간주되지만, BeeGFS 서비스를 다시 시작해야 할 경우 유지보수 시간이나 근무 시간 외에 실행하는 것이 좋습니다. 이러한 재시작으로 인해 일반적으로 응용 프로그램 오류가 발생하지는 않지만 성능이 저하될 수 있습니다(일부 응용 프로그램이 다른 응용 프로그램보다 더 잘 처리할 수 있음).

또한 Ansible을 다시 실행하는 것은 전체 클러스터를 최적의 상태로 되돌리는 옵션이며, 경우에 따라 PC를 사용할 때보다 클러스터의 상태를 더 쉽게 복구할 수 있습니다. 특히 어떤 이유로 클러스터가 중단된 비상 상황에서는 모든 노드가 다시 실행 중인 Ansible을 사용하면 PC를 사용하는 것보다 신속하고 안정적으로 클러스터를 복구할 수 있습니다.
