---
sidebar: sidebar 
permalink: administer/clusters-stop-start-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, stop, start 
summary: 정상적으로 HA 클러스터를 중지 및 시작합니다. 
---
= 클러스터를 중지하고 시작합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
정상적으로 HA 클러스터를 중지 및 시작합니다.



== 개요

이 섹션에서는 BeeGFS 클러스터를 정상적으로 종료하고 다시 시작하는 방법에 대해 설명합니다. 이러한 작업이 필요할 수 있는 시나리오에는 전기 유지보수 또는 데이터 센터 또는 랙 간 마이그레이션이 포함됩니다.



== 단계

어떤 이유로든 전체 BeeGFS 클러스터를 중지하고 모든 서비스를 종료해야 하는 경우 다음을 실행합니다.

[source, console]
----
pcs cluster stop --all
----
또한 개별 노드에서 클러스터를 중지할 수도 있습니다(다른 노드로 자동으로 서비스 페일오버). 먼저 노드를 대기 상태로 두는 것이 좋지만(link:clusters-failover-failback.html["페일오버"^]섹션 참조):

[source, console]
----
pcs cluster stop <HOSTNAME>
----
모든 노드에서 클러스터 서비스 및 리소스를 시작하려면 다음을 실행합니다.

[source, console]
----
pcs cluster start --all
----
또는 다음 특정 노드에서 서비스를 시작합니다.

[source, console]
----
pcs cluster start <HOSTNAME>
----
이 시점에서 를 실행합니다 `pcs status` 모든 노드에서 클러스터와 BeeGFS 서비스가 시작되는지, 그리고 원하는 노드에서 서비스가 실행되고 있는지 확인합니다.


TIP: 클러스터의 크기에 따라 전체 클러스터가 중지되거나 에서 시작될 때까지 몇 초~몇 분 정도 걸릴 수 있습니다 `pcs status`. If(경우 `pcs cluster <COMMAND>` "Ctrl+C"를 실행하여 명령을 취소하기 전에 5분 이상 작동이 멈추고 클러스터의 각 노드에 로그인하여 를 사용합니다 `pcs status` 해당 노드에서 클러스터 서비스(Corosync/Pacemaker)가 여전히 실행되고 있는지 확인합니다. 클러스터가 여전히 활성 상태인 모든 노드에서 클러스터를 차단하는 리소스를 확인할 수 있습니다. 문제를 수동으로 해결하고 명령을 완료하거나 다시 실행하여 나머지 서비스를 중지할 수 있습니다.
