---
sidebar: sidebar 
permalink: administer/clusters-update-ha-services.html 
keywords: Cluster, Administration, Update, Upgrade, Pacemaker, Corosync 
summary: HA 클러스터에서 심장박동기 및 Corosync 패키지를 업그레이드하는 단계입니다. 
---
= HA 클러스터의 페이스 메이커 및 Corosync 패키지를 업그레이드합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
HA 클러스터의 심장박동기 및 Corosync 패키지를 업그레이드하려면 다음 단계를 수행하십시오.



== 개요

페이스 메이커와 Corosync를 업그레이드하면 새로운 기능, 보안 패치 및 성능 향상의 이점을 누릴 수 있습니다.



== 업그레이드 접근 방식

클러스터를 업그레이드하는 데에는 롤링 업그레이드 또는 전체 클러스터 종료라는 두 가지 권장 방법이 있습니다. 각 접근 방식에는 고유한 장점과 단점이 있습니다. 업그레이드 절차는 심장박동기 릴리스 버전에 따라 다를 수 있습니다. ClusterLabs의 link:https://clusterlabs.org/projects/pacemaker/doc/3.0/Pacemaker_Administration/html/upgrading.html["심장박동기 클러스터 업그레이드"^]설명서를 참조하여 사용할 방법을 결정합니다. 업그레이드 방법을 따르기 전에 다음 사항을 확인하십시오.

* NetApp BeeGFS 솔루션 내에서 새로운 페이스 메이커 및 Corosync 패키지가 지원됩니다.
* BeeGFS 파일 시스템 및 Pacemaker 클러스터 구성에 유효한 백업이 있습니다.
* 클러스터가 정상 상태입니다.




=== 롤링 업그레이드

이 방법은 클러스터에서 각 노드를 제거하고 업그레이드한 다음 모든 노드에서 새 버전이 실행될 때까지 클러스터에 다시 도입하는 것입니다. 이렇게 하면 클러스터가 운영 상태로 유지되므로 대규모 HA 클러스터에 이상적이지만, 프로세스 중에 혼합 버전을 실행할 위험이 있습니다. 2노드 클러스터에서 이 접근 방식은 사용하지 않아야 합니다.

. 각 BeeGFS 서비스가 1차 노드에서 실행되고 있는 상태에서 클러스터가 최적의 상태인지 확인합니다. 자세한 내용은 을 link:clusters-examine-state.html["클러스터의 상태를 검사합니다"^] 참조하십시오.
. 업그레이드할 노드를 대기 모드로 전환하여 모든 BeeGFS 서비스를 방전하거나 이동합니다.
+
[source, console]
----
pcs node standby <HOSTNAME>
----
. 다음을 실행하여 노드의 서비스가 소진되었는지 확인합니다.
+
[source, console]
----
pcs status
----
+
대기 상태인 노드에 대해 보고된 서비스가 `Started` 없는지 확인합니다.

+

NOTE: 클러스터 크기에 따라 서비스가 자매 노드로 이동하는 데 몇 초 또는 몇 분이 걸릴 수 있습니다. BeeGFS 서비스가 자매 노드에서 시작되지 않는 경우 를 참조하십시오link:clusters-troubleshoot.html["문제 해결 설명서"^].

. 노드에서 클러스터를 종료합니다.
+
[source, console]
----
pcs cluster stop <HOSTNAME>
----
. 노드에서 심장박동기, Corosync 및 PCS 패키지를 업그레이드합니다.
+

NOTE: 패키지 관리자 명령은 운영 체제에 따라 다릅니다. 다음은 RHEL 8 이상을 실행하는 시스템에 대한 명령입니다.

+
[source, console]
----
dnf update pacemaker-<version>
----
+
[source, console]
----
dnf update corosync-<version>
----
+
[source, console]
----
dnf update pcs-<version>
----
. 노드에서 심장박동기 클러스터 서비스를 시작합니다.
+
[source, console]
----
pcs cluster start <HOSTNAME>
----
. 패키지가 업데이트된 경우 `pcs` 클러스터를 사용하여 노드를 다시 인증합니다.
+
[source, console]
----
pcs host auth <HOSTNAME>
----
. 박동조율기 구성이 여전히 도구에 유효한지 `crm_verify` 확인합니다.
+

NOTE: 클러스터 업그레이드 중에 한 번만 확인하면 됩니다.

+
[source, console]
----
crm_verify -L -V
----
. 노드를 대기 모드에서 해제합니다.
+
[source, console]
----
pcs node unstandby <HOSTNAME>
----
. 모든 BeeGFS 서비스를 기본 노드로 다시 재배치:
+
[source, console]
----
pcs resource relocate run
----
. 모든 노드가 원하는 페이스 메이커, Corosync 및 PCS 버전을 실행할 때까지 클러스터의 각 노드에 대해 이전 단계를 반복합니다.
. 마지막으로, `pcs status` 클러스터를 실행하고 클러스터 상태가 양호한지 확인하고 가 `Current DC` 원하는 페이스 메이커 버전을 보고합니다.
+

NOTE:  `Current DC`'혼합 버전'이 보고되면 클러스터의 노드가 이전 페이스 메이커 버전과 함께 실행되고 있으므로 업그레이드해야 합니다. 업그레이드된 노드가 클러스터에 다시 연결할 수 없거나 리소스가 시작되지 않는 경우, 클러스터 로그를 확인하고 알려진 업그레이드 문제에 대해서는 Pacemaker 릴리즈 노트 또는 사용자 가이드를 참조하십시오.





=== 클러스터 종료를 완료합니다

이 접근 방식에서는 모든 클러스터 노드 및 리소스가 종료되고 노드가 업그레이드된 다음 클러스터가 다시 시작됩니다. 이 방법은 페이스 메이커 및 Corosync 버전이 혼합 버전 구성을 지원하지 않는 경우에 필요합니다.

. 각 BeeGFS 서비스가 1차 노드에서 실행되고 있는 상태에서 클러스터가 최적의 상태인지 확인합니다. 자세한 내용은 을 link:clusters-examine-state.html["클러스터의 상태를 검사합니다"^] 참조하십시오.
. 모든 노드에서 클러스터 소프트웨어(심장박동기 및 Corosync)를 종료합니다.
+

NOTE: 클러스터 크기에 따라 전체 클러스터를 중지하는 데 몇 초 또는 몇 분이 걸릴 수 있습니다.

+
[source, console]
----
pcs cluster stop --all
----
. 모든 노드에서 클러스터 서비스가 종료되면 요구 사항에 따라 각 노드의 심장박동기, Corosync 및 PCS 패키지를 업그레이드합니다.
+

NOTE: 패키지 관리자 명령은 운영 체제에 따라 다릅니다. 다음은 RHEL 8 이상을 실행하는 시스템에 대한 명령입니다.

+
[source, console]
----
dnf update pacemaker-<version>
----
+
[source, console]
----
dnf update corosync-<version>
----
+
[source, console]
----
dnf update pcs-<version>
----
. 모든 노드를 업그레이드한 후 모든 노드에서 클러스터 소프트웨어를 시작합니다.
+
[source, console]
----
pcs cluster start --all
----
. 패키지가 업데이트된 경우 `pcs` 클러스터의 각 노드를 다시 인증합니다.
+
[source, console]
----
pcs host auth <HOSTNAME>
----
. 마지막으로, `pcs status` 클러스터를 실행하고 클러스터의 상태가 양호한지 확인하고 가 `Current DC` 올바른 심장박동기 버전을 보고합니다.
+

NOTE:  `Current DC`'혼합 버전'이 보고되면 클러스터의 노드가 이전 페이스 메이커 버전과 함께 실행되고 있으므로 업그레이드해야 합니다.


