---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Ansible을 사용하여 BeeGFS 및 HA 클러스터를 업데이트합니다. 
---
= BeeGFS 서비스 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ansible을 사용하여 HA 클러스터에서 실행 중인 BeeGFS 버전을 업데이트하세요.



== 개요

BeeGFS는 `major.minor.patch` 버전 관리 체계를 따릅니다. BeeGFS HA Ansible 역할은 지원되는 각 `major.minor` 버전(예: `beegfs_ha_7_2` 및 `beegfs_ha_7_3`)에 대해 제공됩니다. 각 HA 역할은 Ansible 컬렉션 릴리즈 시점에 제공되는 최신 BeeGFS 패치 버전에 고정되어 있습니다.

BeeGFS의 주요 버전, 마이너 버전 및 패치 버전 간 이동을 포함한 모든 BeeGFS 업그레이드에는 Ansible을 사용해야 합니다. BeeGFS를 업데이트하려면 먼저 BeeGFS Ansible 컬렉션을 업데이트해야 하며, 이 과정에서 배포/관리 자동화 및 기본 HA 클러스터에 대한 최신 수정 사항과 개선 사항도 함께 가져와집니다. 컬렉션을 최신 버전으로 업데이트한 후에도  `-e "beegfs_ha_force_upgrade=true"`가 설정된 상태에서  `ansible-playbook`을 실행하기 전까지는 BeeGFS가 업그레이드되지 않습니다. 각 업그레이드에 대한 자세한 내용은 현재 버전의 link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["BeeGFS 업그레이드 설명서"^]을 참조하십시오.


NOTE: BeeGFS 8로 업그레이드하는 경우 link:clusters-upgrade-beegfs-v8.html["BeeGFS 8로 업그레이드"] 절차를 참조하십시오.



== 테스트된 업그레이드 경로

다음 업그레이드 경로는 테스트 및 검증을 완료했습니다.

[cols="1,1,1,5"]
|===
| 원본 버전 | 버전 업그레이드 | 멀티 레일 | 세부 정보 


| 7.2.6 | 7.3.2 | 예 | v3.0.1에서 v3.1.0으로 Beegfs 컬렉션을 업그레이드하는 중, 멀티레일이 추가되었습니다 


| 7.2.6 | 7.2.8 | 아니요 | v3.0.1에서 v3.1.0으로 Beegfs 컬렉션 업그레이드 


| 7.2.8 | 7.3.1에서 포함 | 예 | begfs 컬렉션 v3.1.0을 사용하여 업그레이드하십시오. 멀티레일이 추가되었습니다 


| 7.3.1에서 포함 | 7.3.2 | 예 | Beegfs 컬렉션 v3.1.0을 사용하여 업그레이드합니다 


| 7.3.2 | 7.4.1 | 예 | Beegfs 컬렉션 v3.2.0을 사용하여 업그레이드합니다 


| 7.4.1 | 7.4.2 | 예 | Beegfs 컬렉션 v3.2.0을 사용하여 업그레이드합니다 


| 7.4.2 | 7.4.6 | 예 | Beegfs 컬렉션 v3.2.0을 사용하여 업그레이드합니다 


| 7.4.6 | 8.0 | 예 | link:clusters-upgrade-beegfs-v8.html["BeeGFS 8로 업그레이드"] 절차의 지침을 사용하여 업그레이드하십시오. 


| 7.4.6 | 8.1 | 예 | link:clusters-upgrade-beegfs-v8.html["BeeGFS 8로 업그레이드"] 절차의 지침을 사용하여 업그레이드하십시오. 


| 7.4.6 | 8.2 | 예 | link:clusters-upgrade-beegfs-v8.html["BeeGFS 8로 업그레이드"] 절차의 지침을 사용하여 업그레이드하십시오. 
|===


== BeeGFS 업그레이드 단계

다음 섹션에서는 BeeGFS Ansible 컬렉션 및 BeeGFS 자체를 업데이트하는 단계를 제공합니다. BeeGFS 주 버전 또는 부 버전 업데이트에 대한 추가 단계에 특히 주의하십시오.



=== 1단계: BeeGFS 컬렉션 업그레이드

에 액세스하여 컬렉션 업그레이드용 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible 갤럭시"^]에서 다음 명령을 실행합니다.

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
오프라인 컬렉션 업그레이드의 경우 에서 컬렉션을 다운로드하십시오 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible 갤럭시"^] 원하는 을 클릭합니다 `Install Version`` 그리고 나서 `Download tarball`. 타볼을 Ansible 제어 노드로 전송하고 다음 명령을 실행합니다.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
을 참조하십시오 link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["컬렉션 설치 중"^] 를 참조하십시오.



=== 2단계: Ansible 인벤토리 업데이트

클러스터의 Ansible 인벤토리 파일에 필요한 또는 원하는 업데이트를 수행하십시오. 특정 업그레이드 요구 사항에 대한 자세한 내용은 아래 <<버전 업그레이드 참고 사항>> 섹션을 참조하십시오. BeeGFS HA 인벤토리 구성에 대한 일반 정보는 link:../custom/architectures-inventory-overview.html["Ansible 인벤토리 개요"^] 섹션을 참조하십시오.



=== 3단계: Ansible 플레이북 업데이트(주 버전 또는 부 버전을 업데이트하는 경우에만)

주 버전 또는 부 버전 간에 이동하는 경우 `playbook.yml` 클러스터를 배포하고 유지 관리하는 데 사용되는 파일에서 원하는 버전을 반영하도록 역할의 이름을 `beegfs_ha_<VERSION>` 업데이트합니다. 예를 들어 BeeGFS 7.4를 배포하려는 경우 다음과 같은 이점이 `beegfs_ha_7_4`있습니다.

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
이 플레이북 파일의 내용에 대한 자세한 link:../custom/architectures-deploy-ha-cluster.html["BeeGFS HA 클러스터를 구축합니다"^]내용은 섹션을 참조하십시오.



=== 4단계: BeeGFS 업그레이드를 실행합니다

BeeGFS 업데이트 적용하기:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
BeeGFS HA 역할에서 다루는 비하인드 스토리:

* 각 BeeGFS 서비스가 기본 노드에 위치하도록 클러스터가 최적의 상태인지 확인합니다.
* 클러스터를 유지보수 모드로 전환합니다.
* HA 클러스터 구성 요소를 업데이트합니다(필요한 경우).
* 다음과 같이 각 파일 노드를 한 번에 하나씩 업그레이드합니다.
+
** 대기 노드에 배치하고 서비스를 보조 노드로 페일오버합니다.
** BeeGFS 패키지를 업그레이드합니다.
** 서비스 대체.


* 클러스터를 유지보수 모드 외부로 이동합니다.




== 버전 업그레이드 참고 사항



=== BeeGFS 버전 7.2.6 또는 7.3.0에서 업그레이드



==== 연결 기반 인증에 대한 변경 사항

BeeGFS 버전 7.3.2 이상에서는 연결 기반 인증이 구성되어 있어야 합니다. 다음 중 하나라도 구성되지 않으면 서비스가 시작되지 않습니다.

*  `connAuthFile` 또는 를 지정합니다.
* 서비스의 구성 파일에서  `connDisableAuthentication=true` 설정.


보안을 위해 연결 기반 인증을 활성화하는 것을 적극 권장합니다. 자세한 내용은 link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["BeeGFS 연결 기반 인증"^]을 참조하십시오.

 `beegfs_ha*` 역할은 인증 파일을 자동으로 생성하여 다음 위치로 배포합니다.

* 클러스터의 모든 파일 노드
*  `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`의 Ansible 제어 노드


 `beegfs_client` 역할은 파일이 존재할 경우 자동으로 감지하여 클라이언트에 적용합니다.


WARNING:  `beegfs_client` 역할을 사용하여 클라이언트를 구성하지 않은 경우 각 클라이언트에 인증 파일을 수동으로 배포하고  `beegfs-client.conf` 파일에서  `connAuthFile` 설정을 구성해야 합니다. 연결 기반 인증이 없는 BeeGFS 버전에서 업그레이드하는 경우  `group_vars/ha_cluster.yml`에서  `beegfs_ha_conn_auth_enabled: false`를 설정하여 업그레이드 중에 연결 기반 인증을 비활성화하지 않으면 클라이언트가 액세스 권한을 잃게 됩니다(권장하지 않음).

자세한 내용 및 다른 구성 옵션은 link:../custom/architectures-inventory-common-file-node-configuration.html["일반 파일 노드 구성을 지정합니다"^] 섹션의 연결 인증 구성 단계를 참조하십시오.
