---
sidebar: sidebar 
permalink: administer/clusters-expand-shrink-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: 클러스터에서 구성 요소를 추가하거나 제거합니다. 
---
= 클러스터를 확장 또는 축소합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
클러스터에서 구성 요소를 추가하거나 제거합니다.



== 개요

이 섹션에서는 BeeGFS HA 클러스터의 크기를 조정하는 다양한 고려 사항 및 옵션에 대해 설명합니다. 일반적으로 클러스터 크기는 구성 요소를 추가 또는 제거하여 조정합니다. 구성 요소는 일반적으로 2개의 파일 노드를 HA 쌍으로 설정합니다. 필요한 경우 개별 파일 노드(또는 다른 유형의 클러스터 노드)를 추가하거나 제거할 수도 있습니다.



== 클러스터에 빌딩 블록 추가



=== 고려 사항

추가 구성 요소를 추가하여 클러스터를 늘리는 것은 간단한 프로세스입니다. 시작하기 전에 각 개별 HA 클러스터의 최소 및 최대 클러스터 노드 수에 대한 제한을 염두에 두고, 기존 HA 클러스터에 노드를 추가하거나 새로운 HA 클러스터를 생성해야 하는지 확인합니다. 일반적으로 각 구성 요소는 2개의 파일 노드로 구성되지만, 3개의 노드는 쿼럼(quorum)을 설정하기 위해 클러스터당 최소 노드 수이고 10개는 권장(테스트)입니다. 고급 시나리오의 경우 2노드 클러스터를 구축할 때 BeeGFS 서비스를 실행하지 않는 단일 "Tiebreaker" 노드를 추가할 수 있습니다. 이러한 배포를 고려 중인 경우 NetApp 지원에 문의하십시오.

클러스터를 확장하는 방법을 결정할 때는 이러한 제한 사항과 향후 클러스터 확장에 대한 예상에 유의하십시오. 예를 들어, 6노드 클러스터가 있고 4노드를 더 추가해야 하는 경우 새 HA 클러스터를 시작하는 것이 좋습니다.


TIP: 단일 BeeGFS 파일 시스템은 여러 독립 HA 클러스터로 구성될 수 있습니다. 따라서 파일 시스템은 기본 HA 클러스터 구성 요소의 권장/하드 제한보다 훨씬 높은 확장성을 유지할 수 있습니다.



=== 단계

구성 요소를 클러스터에 추가할 때 `host_vars` 각 새 파일 노드 및 블록 노드(E-Series 스토리지)에 대한 파일을 생성해야 합니다. 이러한 호스트의 이름은 생성할 새 리소스와 함께 인벤토리에 추가해야 합니다.  `group_vars`각 새 리소스에 대해 해당 파일을 생성해야 합니다. link:../custom/architectures-overview.html["사용자 지정 아키텍처 사용"^]자세한 내용은 섹션을 참조하십시오.

올바른 파일을 생성한 후 다음 명령을 사용하여 자동화를 다시 실행해야 합니다.

[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----


== 클러스터에서 빌딩 블록 제거

구성 요소를 폐기해야 할 경우에는 다음과 같은 여러 가지 사항을 고려해야 합니다.

* 이 빌딩 블록에서 실행 중인 BeeGFS 서비스는 무엇입니까?
* 파일 노드만 사용 중지되며 블록 노드를 새 파일 노드에 연결해야 합니까?
* 전체 빌딩 블록이 사용 중단된 경우 데이터를 새 빌딩 블록으로 이동하거나, 클러스터의 기존 노드로 분산하거나, 새로운 BeeGFS 파일 시스템 또는 다른 스토리지 시스템으로 이동해야 합니까?
* 이 문제는 중단 중에 발생할 수 있습니까? 아니면 중단 없이 수행해야 합니까?
* 구성 요소를 적극적으로 사용하고 있습니까, 아니면 주로 더 이상 활성 상태가 아니지 않은 데이터가 포함되어 있습니까?


가능한 다양한 시작 지점과 원하는 종료 상태 때문에 NetApp 지원에 문의하여 고객 환경과 요구 사항에 따라 최상의 전략을 파악하고 구현할 수 있습니다.
