---
sidebar: sidebar 
permalink: administer/clusters-overview.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration 
summary: 구축된 BeeGFS HA 클러스터를 관리하는 방법에 대해 알아보십시오. 
---
= 개요, 주요 개념 및 용어
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
구축된 BeeGFS HA 클러스터를 관리하는 방법에 대해 알아보십시오.



== 개요

이 섹션은 구축된 BeeGFS HA 클러스터를 관리해야 하는 클러스터 관리자를 대상으로 합니다. Linux HA 클러스터에 익숙한 사람조차도 이 가이드를 완전히 읽어야 합니다. Ansible을 사용하여 재구성을 수행할 때는 특히 클러스터 관리 방법에 여러 가지 차이점이 있기 때문입니다.



== 주요 개념

이러한 개념 중 일부는 메인 link:../get-started/beegfs-terms.html["용어 및 개념"] 페이지에 소개되었지만 BeeGFS HA 클러스터의 컨텍스트에서 다시 소개하면 도움이 됩니다.

** 클러스터 노드:** 심장박동기 및 Corosync 서비스를 실행하고 HA 클러스터에 참여하는 서버.

** 파일 노드:** 하나 이상의 BeeGFS 관리, 메타데이터 또는 스토리지 서비스를 실행하는 데 사용되는 클러스터 노드입니다.

** 블록 노드:** 파일 노드에 블록 스토리지를 제공하는 NetApp E-Series 스토리지 시스템 이러한 노드는 자체 독립형 HA 기능을 제공하므로 BeeGFS HA 클러스터에 참여하지 않습니다. 각 노드는 블록 계층에서 고가용성을 제공하는 2개의 스토리지 컨트롤러로 구성됩니다.

** BeeGFS 서비스:** BeeGFS 관리, 메타데이터 또는 스토리지 서비스 각 파일 노드는 블록 노드의 볼륨을 사용하여 데이터를 저장하는 하나 이상의 서비스를 실행합니다.

** 빌딩 블록:** BeeGFS 파일 노드, E-Series 블록 노드 및 BeeGFS 서비스를 표준화된 방식으로 구축하여 NetApp 검증 아키텍처에 따라 BeeGFS HA 클러스터/파일 시스템을 간편하게 확장할 수 있습니다. 맞춤형 HA 클러스터도 지원되지만, 확장을 단순화하기 위해 유사한 구성 요소 접근 방식을 따르는 경우가 많습니다.

** BeeGFS HA Cluster:** 블록 노드에서 지원하는 BeeGFS 서비스를 실행하는 데 사용되는 확장 가능한 수의 파일 노드를 통해 BeeGFS 데이터를 고가용성 방식으로 저장합니다. 패키징 및 배포를 위해 Ansible을 사용하여 업계에서 검증된 오픈 소스 구성 요소 페이스 메이커 및 Corosync를 기반으로 합니다.

** 클러스터 서비스: ** 클러스터에 참여하는 각 노드에서 실행 중인 심장박동기 및 Corosync 서비스를 나타냅니다. 참고: 노드가 BeeGFS 서비스를 실행하지 않고 단지 두 개의 파일 노드만 필요한 경우 "Tiebreaker" 노드로 클러스터에 참여할 수 있습니다.

** 클러스터 리소스:** 클러스터에서 실행 중인 각 BeeGFS 서비스에 대해 BeeGFS 모니터링 리소스와 BeeGFS 타겟, IP 주소(부동 IP) 및 BeeGFS 서비스 자체에 대한 리소스가 포함된 리소스 그룹이 표시됩니다.

Ansible:** 소프트웨어 프로비저닝, 구성 관리 및 애플리케이션 배포를 위한 도구로 인프라를 코드로 구현할 수 있습니다. BeeGFS HA 클러스터를 패키지화하여 NetApp에서 BeeGFS 구축, 재구성 및 업데이트 프로세스를 간소화합니다.

** PCS:** 클러스터의 파일 노드에서 사용할 수 있는 명령줄 인터페이스입니다. 이 인터페이스는 클러스터의 노드 및 리소스 상태를 쿼리하고 제어하는 데 사용됩니다.



== 일반 용어

** 장애 조치:** 각 BeeGFS 서비스에는 해당 노드에 장애가 발생하지 않는 한 실행되는 기본 파일 노드가 있습니다. 비기본/보조 파일 노드에서 BeeGFS 서비스를 실행하는 경우 페일오버 중인 것으로 표시됩니다.

** 페일백:** 비기본 파일 노드에서 기본 설정 노드로 BeeGFS 서비스를 이동하는 동작

** HA 쌍:** 동일한 블록 노드 세트에 액세스할 수 있는 두 개의 파일 노드를 HA 쌍이라고도 합니다. 이는 NetApp 전체에서 사용되는 일반적인 용어로 서로 "이어갈" 수 있는 2개의 스토리지 컨트롤러 또는 노드를 참조하는 데 사용됩니다.

** 유지 관리 모드: ** 모든 리소스 모니터링을 비활성화하고 심장박동기 장치가 클러스터의 리소스를 이동하거나 관리하지 못하게 합니다(의 섹션 참조link:clusters-maintenance-mode.html["유지보수 모드"^]).

** HA 클러스터:** 클러스터의 여러 노드 간에 페일오버하여 가용성이 높은 BeeGFS 파일 시스템을 생성할 수 있는 BeeGFS 서비스를 실행하는 하나 이상의 파일 노드. 파일 노드는 클러스터에서 BeeGFS 서비스의 하위 집합을 실행할 수 있는 HA 쌍으로 구성되는 경우가 많습니다.
