---
sidebar: sidebar 
permalink: administer/clusters-replace-file-nodes.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, replace 
summary: 원래 서버에 오류가 있는 경우 파일 노드를 교체합니다. 
---
= 파일 노드를 바꿉니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
원래 서버에 오류가 있는 경우 파일 노드를 교체합니다.



== 개요

다음은 클러스터의 파일 노드를 교체하는 데 필요한 단계에 대한 개요입니다. 다음 단계에서는 하드웨어 문제로 인해 파일 노드가 실패했으며 동일한 새 파일 노드로 교체된다고 가정합니다.



== 단계:

. 파일 노드를 물리적으로 교체하고 블록 노드 및 스토리지 네트워크에 대한 모든 케이블 연결을 복원합니다.
. Red Hat 서브스크립션 추가를 포함하여 파일 노드에 운영 체제를 다시 설치합니다.
. 파일 노드에서 관리 및 BMC 네트워킹을 구성합니다.
. 호스트 이름, IP, PCIe-논리 인터페이스 매핑 또는 새 파일 노드에 대해 변경된 사항이 있는 경우 Ansible 인벤토리를 업데이트합니다. 일반적으로 노드가 동일한 서버 하드웨어로 교체되었고 원래 네트워크 구성을 사용하는 경우에는 필요하지 않습니다.
+
.. 예를 들어 호스트 이름이 변경된 경우 노드의 인벤토리 파일을 생성하거나 이름을 변경합니다 (`host_vars/<NEW_NODE>.yml``)를 선택한 다음 Ansible 인벤토리 파일에 저장합니다 (`inventory.yml`)에서 이전 노드의 이름을 새 노드 이름으로 바꿉니다.
+
[source, console]
----
all:
    ...
    children:
    ha_cluster:
        children:
        mgmt:
            hosts:
            node_h1_new:   # Replaced "node_h1" with "node_h1_new"
            node_h2:
----


. 클러스터의 다른 노드 중 하나에서 이전 노드를 제거합니다. `pcs cluster node remove <HOSTNAME>`.
+

IMPORTANT: 이 단계를 실행하기 전에 진행하지 마십시오.

. Ansible 제어 노드에서:
+
.. 다음을 사용하여 이전 SSH 키를 제거합니다.
+
[source, console]
----
`ssh-keygen -R <HOSTNAME_OR_IP>`
----
.. 바꾸기 노드에 대해 암호 없는 SSH를 다음으로 구성:
+
[source, console]
----
ssh-copy-id <USER>@<HOSTNAME_OR_IP>
----


. Ansible 플레이북을 다시 실행하여 노드를 구성하고 클러스터에 추가합니다.
+
[source, console]
----
ansible-playbook -i <inventory>.yml <playbook>.yml
----
. 이때 를 실행합니다 `pcs status` 교체된 노드가 나열되고 서비스가 실행 중인지 확인합니다.

