---
sidebar: sidebar 
permalink: administer/clusters-update-storage-array.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade, SANtricityOS, firmware, drive 
summary: HA 클러스터의 E-Series 스토리지 어레이를 업그레이드하는 단계입니다. 
---
= E-Series 스토리지 시스템을 업그레이드합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
HA 클러스터의 E-Series 스토리지 어레이 구성 요소를 업그레이드하려면 다음 단계를 따르십시오.



== 개요

최신 펌웨어로 HA 클러스터의 NetApp E-Series 스토리지 어레이를 최신 상태로 유지하면 최적의 성능과 향상된 보안을 보장할 수 있습니다. 스토리지 어레이용 펌웨어 업데이트는 SANtricity OS, NVSRAM 및 드라이브 펌웨어 파일을 통해 적용됩니다.


NOTE: 스토리지 어레이는 HA 클러스터를 온라인으로 업그레이드할 수 있지만 모든 업그레이드를 위해 클러스터를 유지보수 모드로 전환하는 것이 좋습니다.



== 블록 노드 업그레이드 단계

다음 단계에서는 `Netapp_Eseries.Santricity` Ansible 컬렉션을 사용하여 스토리지 어레이의 펌웨어를 업데이트하는 방법을 간략히 설명합니다. 계속하기 전에 link:https://docs.netapp.com/us-en/e-series/upgrade-santricity/overview-upgrade-consider-task.html["업그레이드 고려 사항"^]E-Series 시스템 업데이트에 대한 를 검토하십시오.


NOTE: SANtricity OS 11.80 이상 릴리즈로 업그레이드하는 것은 11.70.5P1부터 가능합니다. 추가 업그레이드를 적용하기 전에 먼저 스토리지 어레이를 11.70.5P1로 업그레이드해야 합니다.

. Ansible 제어 노드에서 최신 SANtricity Ansible Collection을 사용하고 있는지 확인합니다.
+
** 에 액세스하여 컬렉션 업그레이드용 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible 갤럭시"^]에서 다음 명령을 실행합니다.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.santricity --upgrade
----
** 오프라인 업그레이드의 경우 에서 컬렉션 타르볼을 다운로드하여 link:https://galaxy.ansible.com/ui/repo/published/netapp_eseries/santricity/["Ansible 갤럭시"^]컨트롤 노드로 전송한 후 다음을 실행합니다.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries-santricity-<VERSION>.tar.gz --upgrade
----
+
을 참조하십시오 link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["컬렉션 설치 중"^] 를 참조하십시오.



. 스토리지 배열 및 드라이브에 대한 최신 펌웨어를 가져옵니다.
+
.. 펌웨어 파일을 다운로드합니다.
+
*** * SANtricity OS 및 NVSRAM: * link:https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab["NetApp Support 사이트"^]스토리지 어레이 모델에 맞는 SANtricity OS 및 NVSRAM 최신 릴리스로 이동하여 다운로드합니다.
*** * 드라이브 펌웨어: * 로 link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["E-Series 디스크 펌웨어 사이트입니다"^]이동하여 각 스토리지 배열의 드라이브 모델에 대한 최신 펌웨어를 다운로드합니다.


.. SANtricity OS, NVSRAM 및 드라이브 펌웨어 파일을 Ansible 제어 노드의 `<inventory_directory>/packages` 디렉토리에 저장합니다.


. 필요한 경우 업데이트가 필요한 모든 스토리지 어레이(블록 노드)를 포함하도록 클러스터의 Ansible 인벤토리 파일을 업데이트합니다. 지침은 link:../custom/architectures-inventory-overview.html["Ansible 인벤토리 개요"^]섹션을 참조하십시오.
. 1차 노드에서 각 BeeGFS 서비스를 통해 클러스터가 최적의 상태로 유지되도록 합니다. 자세한 내용은 을 link:clusters-examine-state.html["클러스터의 상태를 검사합니다"^] 참조하십시오.
. 의 지침에 따라 클러스터를 유지보수 모드로 link:clusters-maintenance-mode.html["클러스터를 유지보수 모드로 전환합니다"^]전환합니다.
. 이라는 새 Ansible 플레이북을 `update_block_node_playbook.yml`생성합니다. SANtricity OS, NVSRAM 및 드라이브 펌웨어 버전을 원하는 업그레이드 경로로 대체하여 플레이북에 다음 콘텐츠를 채웁니다.
+
....
- hosts: eseries_storage_systems
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.santricity
  vars:
    eseries_firmware_firmware: "packages/<SantricityOS>.dlp"
    eseries_firmware_nvsram: "packages/<NVSRAM>.dlp"
    eseries_drive_firmware_firmware_list:
      - "packages/<drive_firmware>.dlp"
    eseries_drive_firmware_upgrade_drives_online: true

  tasks:
    - name: Configure NetApp E-Series block nodes.
      import_role:
        name: nar_santricity_management
....
. 업데이트를 시작하려면 Ansible 컨트롤 노드에서 다음 명령을 실행합니다.
+
[listing]
----
ansible-playbook -i inventory.yml update_block_node_playbook.yml
----
. 플레이북이 완료된 후 각 스토리지 어레이가 최적의 상태인지 확인합니다.
. 클러스터를 유지보수 모드에서 해제하고 각 BeeGFS 서비스가 기본 노드에 있을 때 클러스터가 최적의 상태인지 확인합니다.

