---
sidebar: sidebar 
permalink: custom/architectures-overview.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: BeeGFS on NetApp 솔루션은 BeeGFS 병렬 파일 시스템을 NetApp E-Series 스토리지 시스템과 결합하여 까다로운 워크로드에 대응할 수 있는 안정적이고 확장 가능하며 비용 효율적인 인프라를 제공합니다. 
---
= 개요 및 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ansible을 사용하여 BeeGFS 고가용성 클러스터를 구축할 때 모든 NetApp E/EF-Series 스토리지 시스템을 BeeGFS 블록 노드 및 x86 서버로 BeeGFS 파일 노드로 사용할 수 있습니다.


TIP: 이 섹션에서 사용되는 용어에 대한 정의는 link:../get-started/beegfs-terms.html["용어 및 개념"]페이지에서 확인할 수 있습니다.



== 소개

link:../second-gen/beegfs-solution-overview.html["NetApp 검증 아키텍처"]사전 정의된 참조 구성 및 사이징 지침을 제공하는 한편, 일부 고객 및 파트너는 특정 요구 사항이나 하드웨어 선호도에 보다 적합한 맞춤형 아키텍처를 설계하기를 원할 수 있습니다. NetApp에서 BeeGFS를 선택할 때의 주요 이점 중 하나는 Ansible을 사용하여 BeeGFS 공유 디스크 HA 클러스터를 구축하여 NetApp에서 작성한 HA 구성요소를 통해 클러스터 관리를 단순화하고 안정성을 높일 수 있다는 것입니다. NetApp에 맞춤형 BeeGFS 아키텍처를 구축할 때는 Ansible을 사용하여 유연한 하드웨어 제품군에서 어플라이언스 같은 접근 방식을 유지 관리합니다.

이 섹션에서는 NetApp 하드웨어에서 BeeGFS 파일 시스템을 구축하고 Ansible을 사용하여 BeeGFS 파일 시스템을 구성하는 데 필요한 일반적인 단계를 간략하게 설명합니다. BeeGFS 파일 시스템 설계와 관련된 모범 사례 및 최적화된 예제에 대한 자세한 link:../second-gen/beegfs-solution-overview.html["NetApp 검증 아키텍처"]내용은 섹션을 참조하십시오.



== 구축 개요

일반적으로 BeeGFS 파일 시스템을 구축하려면 다음 단계를 수행해야 합니다.

* 초기 설정:
+
** 하드웨어 설치/케이블 연결
** 파일 및 블록 노드 설정
** Ansible 제어 노드를 설정합니다.


* BeeGFS 파일 시스템을 Ansible 인벤토리로 정의합니다.
* 파일 및 블록 노드 기준으로 Ansible을 실행하여 BeeGFS 구축
+
** 선택적으로 클라이언트를 설정하고 BeeGFS를 마운트합니다.




다음 섹션에서는 이러한 단계에 대해 자세히 설명합니다.

[NOTE]
====
Ansible은 다음을 비롯한 모든 소프트웨어 프로비저닝 및 구성 작업을 처리합니다.

* 블록 노드에서 볼륨 생성/매핑
* 파일 노드에서 볼륨 포맷/튜닝
* 파일 노드에 소프트웨어 설치/구성
* HA 클러스터 설정 및 BeeGFS 리소스 및 파일 시스템 서비스 구성


====


== 요구 사항

Ansible에서 BeeGFS에 대한 지원은 에서 제공됩니다 link:https://galaxy.ansible.com/netapp_eseries/beegfs["Ansible 갤럭시"] BeeGFS HA 클러스터의 포괄적인 구축 및 관리를 자동화하는 역할 및 모듈 모음입니다.

BeeGFS 자체는 <major>.<minor>.<patch> 버전 관리 체계에 따라 버전이 지정되며, 이 컬렉션은 지원되는 각 <major>.<minor> 버전의 BeeGFS에 대한 역할을 유지합니다. 예를 들어 BeeGFS 7.2 또는 BeeGFS 7.3과 같은 BeeGFS 버전이 있습니다. 컬렉션에 대한 업데이트가 릴리스되면 각 역할의 패치 버전이 해당 릴리즈 지점에 대해 사용 가능한 최신 BeeGFS 버전을 가리키도록 업데이트됩니다(예: 7.2.8). 각 버전의 컬렉션은 특정 Linux 배포판과 버전에서도 테스트되어 지원됩니다. 현재 파일 노드의 경우 Red Hat이고, 클라이언트의 경우 Red Hat과 Ubuntu입니다. 다른 배포판 실행이 지원되지 않으며 다른 버전(특히 다른 주요 버전)을 실행하는 것은 권장되지 않습니다.



=== Ansible 컨트롤 노드

이 노드에는 BeeGFS 관리에 사용되는 인벤토리 및 Playbook이 포함됩니다. 다음과 같은 요구 사항이 있습니다.

* Ansible 6.x(Ansible-코어 2.13)
* Python 3.6 (이상)
* Python(PIP) 패키지: ipaddr 및 netaddr


또한 제어 노드에서 모든 BeeGFS 파일 노드 및 클라이언트로 암호 없는 SSH를 설정하는 것이 좋습니다.



=== BeeGFS 파일 노드

파일 노드는 Red Hat Enterprise Linux(RHEL) 9.4를 실행해야 하며, 필수 패키지(pacemaker, corosync, fence-agents-all, resource-agents)가 포함된 HA 저장소에 액세스할 수 있어야 합니다. 예를 들어, 다음 명령을 실행하여 RHEL 9에서 해당 저장소를 활성화할 수 있습니다.

[source, bash]
----
subscription-manager repo-override repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
----


=== BeeGFS 클라이언트 노드

BeeGFS 클라이언트 Ansible 역할을 사용하여 BeeGFS 클라이언트 패키지를 설치하고 BeeGFS 마운트를 관리할 수 있습니다. 이 역할은 RHEL 9.4 및 Ubuntu 22.04에서 테스트되었습니다.

Anabilities를 사용하여 BeeGFS 클라이언트를 설정하고 BeeGFS를 마운트하지 않는 경우 link:https://doc.beegfs.io/latest/release_notes.html#supported-linux-distributions-and-kernels["BeeGFS는 Linux 배포 및 커널을 지원했습니다"] 사용할 수 있습니다.
