---
sidebar: sidebar 
permalink: custom/architectures-inventory-beegfs-metadata.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'BeeGFS 서비스는 그룹 변수(group_VAR)를 사용하여 구성됩니다.' 
---
= BeeGFS 메타데이터 서비스를 정의합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS 서비스는 그룹 변수(group_VAR)를 사용하여 구성됩니다.



== 개요

이 섹션에서는 BeeGFS 메타데이터 서비스 정의에 대해 설명합니다. 특정 파일 시스템에 대한 HA 클러스터에 이 유형의 서비스가 하나 이상 있어야 합니다. 이 서비스를 구성하는 데는 다음 사항이 포함됩니다.

* 서비스 유형(메타데이터)
* 이 BeeGFS 서비스에만 적용해야 하는 구성을 정의합니다.
* 이 서비스에 연결할 수 있는 하나 이상의 부동 IP(논리 인터페이스)를 구성합니다.
* 이 서비스에 대한 데이터를 저장할 볼륨 위치/방법 지정(BeeGFS 메타데이터 타겟)




== 단계

link:architectures-plan-file-system.html["파일 시스템 계획"^]섹션을 참조하여 `group_vars/meta_<ID>.yml` 클러스터의 각 메타데이터 서비스에 대해 에서 파일을 생성하고 다음과 같이 채웁니다.

. 이 파일이 BeeGFS 메타데이터 서비스에 대한 구성을 나타냅니다.
+
[source, yaml]
----
beegfs_service: metadata
----
. 이 BeeGFS 서비스에만 적용해야 하는 구성을 정의합니다. 최소한 원하는 TCP 및 UDP 포트를 지정해야 하지만 에서 지원되는 구성 매개 변수는 모두 지정해야 합니다 `beegfs-meta.conf` 또한 포함될 수 있습니다. 참고 다음 매개 변수는 자동으로/다른 위치에 구성되며 여기에서 지정하면 안 됩니다. `sysMgmtdHost`, `storeMetaDirectory`, `connAuthFile`, `connDisableAuthentication`, `connInterfacesFile`, 및 `connNetFilterFile`.
+
[source, yaml]
----
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: <TCP PORT>
  connMetaPortUDP: <UDP PORT>
  tuneBindToNumaZone: <NUMA ZONE> # Recommended if using file nodes with multiple CPU sockets.
----
. 다른 서비스 및 클라이언트가 이 서비스에 연결하는 데 사용할 하나 이상의 부동 IP를 구성합니다. 이렇게 하면 BeeGFS가 자동으로 설정됩니다 `connInterfacesFile` 옵션):
+
[source, yaml]
----
floating_ips:
  - <INTERFACE>:<IP/SUBNET> # Primary interface. Ex. i1b:100.127.101.1/16
  - <INTERFACE>:<IP/SUBNET> # Secondary interface(s) as needed.
----
. 선택적으로, 나가는 통신에 사용할 수 있는 하나 이상의 허용된 IP 서브넷을 지정합니다(이 경우 BeeGFS가 자동으로 설정됩니다) `connNetFilterFile` 옵션):
+
[source, yaml]
----
filter_ip_ranges:
  - <SUBNET>/<MASK> # Ex. 192.168.10.0/24
----
. 다음 지침에 따라 이 서비스가 데이터를 저장할 BeeGFS 메타데이터 타겟을 지정합니다. 이렇게 하면 가 자동으로 구성됩니다 `storeMetaDirectory` 옵션):
+
.. 여러 BeeGFS 서비스/타겟에 동일한 스토리지 풀 또는 볼륨 그룹 이름을 사용할 수 있으므로 동일한 스토리지 풀 또는 볼륨 그룹 이름을 사용하기만 하면 됩니다 `name`, `raid_level`, `criteria_*`, 및 `common_*` 각 서비스에 대한 구성(각 서비스에 대해 나열된 볼륨은 서로 달라야 함)
.. 볼륨 크기는 스토리지 풀/볼륨 그룹의 백분율로 지정해야 하며, 특정 스토리지 풀/볼륨 그룹을 사용하는 모든 서비스/볼륨에서 합계가 100을 초과해서는 안 됩니다. 참고 SSD를 사용할 경우 SSD 성능 및 마모 수명을 최대화하기 위해 볼륨 그룹에 여유 공간을 두는 것이 좋습니다(link:../second-gen/beegfs-deploy-recommended-volume-percentages.html["여기"^]자세한 내용을 보려면 클릭).
.. 을 클릭합니다 link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["여기"^] 에서 사용할 수 있는 전체 구성 옵션 목록을 확인하십시오 `eseries_storage_pool_configuration`. 과 같은 일부 옵션을 확인합니다 `state`, `host`, `host_type`, `workload_name`, 및 `workload_metadata` 및 볼륨 이름은 자동으로 생성되며 여기에서 지정할 수 없습니다.




[source, yaml]
----
beegfs_targets:
  <BLOCK_NODE>: # The name of the block node as found in the Ansible inventory. Ex: netapp_01
    eseries_storage_pool_configuration:
      - name: <NAME> # Ex: beegfs_m1_m2_m5_m6
        raid_level: <LEVEL> # One of: raid1, raid5, raid6, raidDiskPool
        criteria_drive_count: <DRIVE COUNT> # Ex. 4
        common_volume_configuration:
          segment_size_kb: <SEGMENT SIZE> # Ex. 128
        volumes:
          - size: <PERCENT> # Percent of the pool or volume group to allocate to this volume. Ex. 1
            owning_controller: <CONTROLLER> # One of: A, B
----
을 클릭합니다 link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/group_vars/meta_01.yml["여기"^] BeeGFS 메타데이터 서비스를 나타내는 전체 인벤토리 파일의 예
