---
sidebar: sidebar 
permalink: custom/architectures-inventory-common-block-node-configuration.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: '그룹 변수(group_vars)를 사용하여 일반 블록 노드 구성을 지정합니다.' 
---
= 일반 블록 노드 구성을 지정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
그룹 변수(group_vars)를 사용하여 일반 블록 노드 구성을 지정합니다.



== 개요

모든 블록 노드에 대해 사과해야 하는 구성은 에 정의되어 있습니다 `group_vars/eseries_storage_systems.yml`. 일반적으로 다음과 같은 기능이 있습니다.

* Ansible 제어 노드를 블록 노드로 사용되는 E-Series 스토리지 시스템에 연결하는 방법에 대한 자세한 정보
* 노드에서 실행해야 하는 펌웨어, NVSRAM 및 드라이브 펌웨어 버전
* 캐시 설정, 호스트 구성 및 볼륨 프로비저닝 방법에 대한 설정을 포함한 글로벌 구성



NOTE: 이 파일에 설정된 옵션은 혼합 하드웨어 모델을 사용 중이거나 각 노드에 대해 다른 암호를 사용하는 경우와 같이 개별 블록 노드에서도 정의할 수 있습니다. 개별 블록 노드의 구성은 이 파일의 구성보다 우선합니다.



== 단계

파일을 만듭니다 `group_vars/eseries_storage_systems.yml` 다음과 같이 채웁니다.

. Ansible은 SSH를 사용하여 블록 노드에 연결하지 않고 REST API를 사용합니다. 이를 위해 다음을 설정해야 합니다.
+
[source, yaml]
----
ansible_connection: local
----
. 각 노드를 관리할 사용자 이름과 암호를 지정합니다. 사용자 이름은 선택적으로 생략할 수 있으며 기본적으로 admin이 됩니다. 그렇지 않으면 관리자 권한이 있는 계정을 지정할 수 있습니다. 또한 SSL 인증서를 확인해야 하는지 무시해야 하는지 여부를 지정합니다.
+
[source, yaml]
----
eseries_system_username: admin
eseries_system_password: <PASSWORD>
eseries_validate_certs: false
----
+

WARNING: 암호를 일반 텍스트로 나열하는 것은 권장되지 않습니다. Ansible 볼트를 사용하거나 을 제공합니다 `eseries_system_password` VAR을(를) 사용하여 Ansible을 실행하는 경우

. 노드에 설치할 컨트롤러 펌웨어, NVSRAM 및 드라이브 펌웨어를 선택적으로 지정합니다. 이러한 파일은 로 다운로드해야 합니다 `packages/` Ansible을 실행하기 전 디렉토리: E-Series 컨트롤러 펌웨어 및 NVSRAM을 다운로드할 수 있습니다 link:https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab/["여기"^] 및 드라이브 펌웨어를 업데이트합니다 link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["여기"^]:
+
[source, yaml]
----
eseries_firmware_firmware: "packages/<FILENAME>.dlp" # Ex. "packages/RCB_11.80GA_6000_64cc0ee3.dlp"
eseries_firmware_nvsram: "packages/<FILENAME>.dlp" # Ex. "packages/N6000-880834-D08.dlp"
eseries_drive_firmware_firmware_list:
  - "packages/<FILENAME>.dlp"
  # Additional firmware versions as needed.
eseries_drive_firmware_upgrade_drives_online: true # Recommended unless BeeGFS hasn't been deployed yet, as it will disrupt host access if set to "false".
----
+

WARNING: 이 구성을 지정하면 Ansible이 추가 프롬프트 없이 컨트롤러 재부팅(필요한 경우)을 비롯한 모든 펌웨어를 자동으로 업데이트합니다. 이는 BeeGFS/호스트 입출력에 영향을 줄 수 있지만 일시적으로 성능이 저하될 수 있습니다.

. 글로벌 시스템 구성 기본값을 조정합니다. 여기에 나열된 옵션과 값은 NetApp 기반의 BeeGFS에 일반적으로 권장되지만 필요한 경우 조정할 수 있습니다.
+
[source, yaml]
----
eseries_system_cache_block_size: 32768
eseries_system_cache_flush_threshold: 80
eseries_system_default_host_type: linux dm-mp
eseries_system_autoload_balance: disabled
eseries_system_host_connectivity_reporting: disabled
eseries_system_controller_shelf_id: 99 # Required by default.
----
. 글로벌 볼륨 프로비저닝 기본값을 구성합니다. 여기에 나열된 옵션과 값은 NetApp 기반의 BeeGFS에 일반적으로 권장되지만 필요한 경우 조정할 수 있습니다.
+
[source, yaml]
----
eseries_volume_size_unit: pct # Required by default. This allows volume capacities to be specified as a percentage, simplifying putting together the inventory.
eseries_volume_read_cache_enable: true
eseries_volume_read_ahead_enable: false
eseries_volume_write_cache_enable: true
eseries_volume_write_cache_mirror_enable: true
eseries_volume_cache_without_batteries: false
----
. 필요한 경우 Ansible에서 스토리지 풀 및 볼륨 그룹을 위한 드라이브를 선택하는 순서를 조정하고 다음 모범 사례를 염두에 두십시오.
+
.. 관리 및/또는 메타데이터 볼륨에 먼저 사용되어야 하는 (잠재적으로 작은) 드라이브와 스토리지 볼륨을 나열합니다.
.. 디스크 쉘프/드라이브 엔클로저 모델을 기준으로 사용 가능한 드라이브 채널 간에 드라이브 선택 순서를 조정해야 합니다. 예를 들어 EF600과 확장 없는 경우 드라이브 0-11은 드라이브 채널 1에 있고 드라이브 12-23은 드라이브 채널에 있습니다. 따라서 드라이브 선택의 균형을 맞추는 전략은 선택입니다 `disk shelf:drive` 99:0, 99:23, 99:1, 99:22 등 하나 이상의 엔클로저가 있는 경우 첫 번째 숫자는 드라이브 쉘프 ID를 나타냅니다.
+
[source, yaml]
----
# Optimal/recommended order for the EF600 (no expansion):
eseries_storage_pool_usable_drives: "99:0,99:23,99:1,99:22,99:2,99:21,99:3,99:20,99:4,99:19,99:5,99:18,99:6,99:17,99:7,99:16,99:8,99:15,99:9,99:14,99:10,99:13,99:11,99:12"
----




을 클릭합니다 link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/group_vars/eseries_storage_systems.yml["여기"^] 일반 블록 노드 구성을 나타내는 전체 인벤토리 파일의 예
