---
sidebar: sidebar 
permalink: custom/architectures-plan-file-system.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Ansible 재고를 구축하기 전에 파일 시스템 배포를 계획하십시오. 
---
= 파일 시스템 계획
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ansible 재고를 구축하기 전에 파일 시스템 배포를 계획하십시오.



== 개요

파일 시스템을 구축하기 전에 클러스터에서 실행 중인 모든 파일 노드, 블록 노드 및 BeeGFS 서비스에 필요한 IP 주소, 포트 및 기타 구성을 정의해야 합니다. 정확한 구성은 클러스터의 아키텍처에 따라 다르지만 이 섹션에서는 일반적으로 적용되는 모범 사례와 후속 단계를 정의합니다.



== 단계

. IP 기반 스토리지 프로토콜(예: iSER, iSCSI, NVMe/IB 또는 NVMe/RoCE)을 사용하여 파일 노드를 블록 노드에 연결하는 경우, 각 구성 요소에 대해 다음 워크시트를 작성하십시오. 단일 빌딩 블록의 각 직접 접속은 고유한 서브넷을 가져야 하며, 클라이언트-서버 접속에 사용되는 서브넷과 중복되지 않아야 합니다.
+
|===


| 파일 노드 | IB 포트 | IP 주소입니다 | 블록 노드 | IB 포트 | 물리적 IP | 가상 IP(HDR IB를 사용하는 EF600용) 


| <HOSTNAME> | <PORT> | <IP/SUBNET> | <HOSTNAME> | <PORT> | <IP/SUBNET> | <IP/SUBNET> 
|===
+

NOTE: 각 빌딩 블록의 파일 및 블록 노드가 직접 연결된 경우 여러 빌딩 블록에 동일한 IP/스키마를 재사용할 수 있습니다.

. 스토리지 네트워크에 InfiniBand 또는 RoCE(RDMA over Converged Ethernet)를 사용하는 경우, 다음 워크시트를 작성하여 HA 클러스터 서비스, BeeGFS 파일 서비스 및 클라이언트가 통신할 수 있는 IP 범위를 결정하십시오.
+
|===
| 목적 | InfiniBand 포트입니다 | IP 주소 또는 범위입니다 


| BeeGFS 클러스터 IP | <INTERFACE(s)> | <RANGE> 


| BeeGFS 관리 | <INTERFACE(s)> | <IP(s)> 


| BeeGFS 메타데이터 | <INTERFACE(s)> | <RANGE> 


| BeeGFS 스토리지 | <INTERFACE(s)> | <RANGE> 


| BeeGFS 클라이언트 | <INTERFACE(s)> | <RANGE> 
|===
+
.. 단일 IP 서브넷을 사용하는 경우 워크시트가 하나만 필요합니다. 그렇지 않으면 두 번째 서브넷에 대한 워크시트도 작성하십시오.


. 위의 내용을 토대로 클러스터의 각 구성 요소에 대해 실행할 BeeGFS 서비스를 정의하는 다음 워크시트를 작성하십시오. 각 서비스에 대해 기본 설정/보조 파일 노드, 네트워크 포트, 부동 IP, NUMA 영역 할당(필요한 경우) 및 대상에 사용할 블록 노드를 지정합니다. 워크시트를 작성할 때 다음 지침을 참조하십시오.
+
.. BeeGFS 서비스 중 하나를 지정합니다 `mgmt.yml`, `meta_<ID>.yml`, 또는 `storage_<ID>.yml` 여기서 ID는 이 파일 시스템에서 해당 유형의 모든 BeeGFS 서비스에 대한 고유 번호입니다. 이 규칙은 각 서비스를 구성하는 파일을 생성하는 동안 다음 섹션에서 이 워크시트를 간단하게 참조할 수 있도록 합니다.
.. BeeGFS 서비스의 포트는 특정 구성 요소 전체에서 고유해야 합니다. 포트 충돌을 방지하기 위해 동일한 포트 번호의 서비스를 동일한 파일 노드에서 실행할 수 없도록 합니다.
.. 필요한 서비스가 둘 이상의 블록 노드 및/또는 스토리지 풀의 볼륨을 사용할 수 있는 경우(모든 볼륨을 동일한 컨트롤러가 소유할 필요는 없음) 또한 여러 서비스에서 동일한 블록 노드 및/또는 스토리지 풀 구성을 공유할 수 있습니다(개별 볼륨은 이후 섹션에서 정의).
+
|===
| BeeGFS 서비스(파일 이름) | 파일 노드 | 포트 | 유동 IP | NUMA 영역 | 블록 노드 | 스토리지 풀 | 소유 컨트롤러 


| <SERVICE TYPE>_<ID>.대칭 | <PREFERRED FILE NODE> <SECONDARY FILE NODE(s)> | <PORT> | <INTERFACE>:<IP/SUBNET> <INTERFACE>:<IP/SUBNET> | <NUMA NODE/ZONE> | <BLOCK NODE> | <STORAGE POOL/VOLUME GROUP> | <A OR B> 
|===




표준 규칙, 모범 사례 및 작성된 예제 워크시트에 대한 자세한 내용은 link:../second-gen/beegfs-deploy-bestpractice.html["모범 사례"^]link:../second-gen/beegfs-deploy-define-inventory.html["BeeGFS 구성 요소를 정의합니다"^]NetApp 검증 아키텍처에서 BeeGFS의 및  섹션을 참조하십시오.
