---
sidebar: sidebar 
permalink: custom-architectures-deploy-playbook-overview.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Ansible을 사용하여 BeeGFS HA 클러스터 구축 및 관리 
---
= Ansible 플레이북 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ansible을 사용하여 BeeGFS HA 클러스터 구축 및 관리



== 개요

이전 섹션에서는 BeeGFS HA 클러스터를 나타내는 Ansible 재고를 구축하는 데 필요한 단계를 안내했습니다. 이 섹션에서는 클러스터를 구축 및 관리하기 위해 NetApp에서 개발한 Ansible 자동화를 소개합니다.



== Ansible: 주요 개념

진행하기 전에 Ansible의 몇 가지 주요 개념을 숙지하는 것이 좋습니다.

* Ansible 인벤토리에 대해 실행할 작업은 * 플레이북 * 으로 알려진 내용에 정의됩니다.
+
** Ansible에서 수행하는 대부분의 작업은 * idemtiple * 으로 설계되어 여러 번 실행할 수 있으므로, 원하는 구성/상태가 중단 없이 적용되었는지, 불필요한 업데이트를 하지 않고 그대로 적용되는지를 확인할 수 있습니다.


* Ansible에서 실행할 수 있는 가장 작은 단위는 * 모듈 * 입니다.
+
** 일반적인 플레이북에서는 여러 모듈을 사용합니다.
+
*** 예: 패키지 다운로드, 구성 파일 업데이트, 서비스 시작/활성화


** NetApp은 모듈을 분산하여 NetApp E-Series 시스템을 자동화합니다.


* 복잡한 자동화는 하나의 역할로 더 잘 패키징됩니다.
+
** 기본적으로 재사용 가능한 플레이북을 배포하기 위한 표준 형식입니다.
** NetApp은 Linux 호스트 및 BeeGFS 파일 시스템에 대한 역할을 분산합니다.






== Ansible용 BeeGFS HA 역할: 주요 개념

NetApp에서 각 버전의 BeeGFS를 구축 및 관리하는 데 필요한 모든 자동화 기능이 Ansible 역할로 패키지되어 의 일부로 배포됩니다 link:https://galaxy.ansible.com/netapp_eseries/beegfs["BeeGFS용 NetApp E-Series Ansible 컬렉션"^]:

* 이 역할은 * 설치 프로그램 * 과 BeeGFS용 최신 * 구축/관리 * 엔진 사이의 어딘가에 있다고 생각할 수 있습니다.
+
** 최신 인프라를 코드 사례 및 철학으로 적용하여 모든 규모의 스토리지 인프라 관리를 단순화합니다.
** 와 유사합니다 link:https://kubernetes.io/docs/setup/production-environment/tools/kubespray/["구베기도"^] Project에서는 전체 Kubernetes 배포를 구축/유지 관리하여 컴퓨팅 인프라를 확장할 수 있습니다.


* NetApp에서 NetApp 솔루션에서 BeeGFS를 패키징, 배포 및 유지 관리하는 데 사용하는 * 소프트웨어 정의 * 형식입니다.
+
** 전체 Linux 배포판이나 큰 이미지를 배포할 필요 없이 "어플라이언스와 유사한" 환경을 조성하기 위해 노력합니다.
** 지능형 Pacemaker/BeeGFS 통합을 제공하는 맞춤형 BeeGFS 타겟, IP 주소, 모니터링을 위해 NetApp에서 작성한 OCF(Open Cluster Framework) 규격 클러스터 리소스 에이전트가 포함되어 있습니다.


* 이 역할은 단순히 "자동화"를 구축하는 것이 아니라 다음을 포함한 전체 파일 시스템 수명주기를 관리하는 데 사용됩니다.
+
** 서비스별 또는 클러스터 전체 구성 변경 및 업데이트 적용
** 하드웨어 문제가 해결된 후 클러스터 복구 및 복구 자동화
** BeeGFS 및 NetApp 볼륨을 사용한 광범위한 테스트 결과를 기준으로 설정된 기본값으로 성능 조정을 단순화합니다.
** 구성 드리프트 확인 및 수정




NetApp은 또한 Ansible 역할을 제공합니다 link:https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_client["BeeGFS 클라이언트"^]필요에 따라 BeeGFS를 설치하고 파일 시스템을 컴퓨팅/GPU/로그인 노드에 마운트하는 데 사용할 수 있습니다.
